name: Score code quality

on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        os: ["ubuntu", "windows", "macos"]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        miniforge-version: latest
    - name: Set up dev environment
      run: |
        pip install pylint
        conda list
        conda list -n daps-hackathon
    - name: Write standard credentials to file
      run: |
        echo "assignment" > src/mongodb.pwd
        echo "" > src/github.token
    - name: Run the main function
      run: |
        python main.py
    - name: Check code quality
      run: |
        conda activate daps-hackathon
        pylint $(git ls-files '*.py')