name: Score code quality

on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up dev environment
      run: |
        $CONDA/bin/conda env create -f environment.yml
        $CONDA/bin/activate daps-hackathon
        pip install pylint
        $CONDA/bin/conda list
        $CONDA/bin/conda list -n daps-hackathon
    - name: Write standard credentials to file
      run: |
        echo "assignment" > src/mongodb.pwd
        echo "" > src/github.token
    - name: Run the main function
      run: |
        $CONDA/bin/conda init
        $CONDA/bin/conda activate daps-hackathon
        python main.py
    - name: Check code quality
      run: |
        $CONDA/bin/conda activate daps-hackathon
        pylint $(git ls-files '*.py')